config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  resources :bios
  resources :laboratories
  get 'jobs' => 'jobs#index'
  get 'contents' => 'contents#index'
  get 'kakomons' => 'kakomons#index'
  get 'links' => 'links#index'
  get 'signup' =>'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  root 'sessions#new'

end

app/models/bio.rb
class Bio < ActiveRecord::Base
end

app/models/professor.rb
class Professor < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  # 与えられた文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続的セッションで使用するユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

    # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

    # ユーザーログインを破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/bios_controller.rb
class BiosController < ApplicationController

  def index
    @bios = Bio.all
  end

  def new
    render :template => "users/show"
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
    def index
      @bios = Bio.all
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @bios = Bio.all
  end
end

app/controllers/kakomons_controller.rb
class KakomonsController < ApplicationController
  def index

  end
end

app/controllers/laboratories_controller.rb
class LaboratoriesController < ApplicationController
  def index
    @professors = Professor.all
  end

  def show
    @professor = Professor.find(params[:id])
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
    @bios = Bio.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # ユーザーログイン後にユーザー情報のページにリダイレクトする
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to user
    else
      # エラーメッセージを作成する
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bios_helper.rb
module BiosHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/kakomons_helper.rb
module KakomonsHelper
end

app/helpers/laboratories_helper.rb
module LaboratoriesHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

  # ユーザーを永続的セッションに記憶する
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # 現在ログインしているユーザーを返す (ユーザーがログイン中の場合のみ)
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

    # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end

    # 永続的セッションを破棄する
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end


    # 現在のユーザーをログアウトする
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bios/_footer.html.slim
.footer.l-box
  address
    | &copy 2016 created by Bio-Z We部　

app/views/bios/_header.html.slim
.pure-menu.pure-menu-horizontal
  a.pure-menu-heading href="./"
    =image_tag("icons3/Primary.png")
  ul.pure-menu-list
    li.pure-menu-item
      =link_to('研究室' , laboratories_path , :class => 'pure-menu-link')
    li.pure-menu-item
      =link_to('過去問道場' , kakomons_path , :class => 'pure-menu-link')
    li.pure-menu-item
      =link_to('就職' , jobs_path , :class => 'pure-menu-link')
    li.pure-menu-item.pure-menu-has-children.pure-menu-allow-hover
      p.pure-menu-link
       | コンテンツ
      ul.pure-menu-children
        li.pure-menu-item
          =link_to('温度、湿度測定', {} , :class => 'pure-menu-link')
        li.pure-menu-item
          =link_to('脈拍の測定', {} ,:class => 'pure-menu-link')
        li.pure-menu-item.pure-menu-disabled
          =link_to('coming soon..', {}, :class => 'pure-menu-link')
    li.pure-menu-item.pure-menu-has-children.pure-menu-allow-hover
      p.pure-menu-link
        | リンク
      ul.pure-menu-children
        li.pure-menu-item
          =link_to('moodle', 'http://mi.el.kyutech.ac.jp/course/index.php?categoryid=8' , :class => 'pure-menu-link')
        li.pure-menu-item
          =link_to('livecampus', 'https://virginia.jimu.kyutech.ac.jp/portal/init.do?userDivision=2&locale=ja' ,:class => 'pure-menu-link')
        li.pure-menu-item
          =link_to('オンラインガイド', 'https://onlineguide.isc.kyutech.ac.jp/guide2015/', :class => 'pure-menu-link')
-if logged_in?
  =link_to('Log in' , login_path, :class => 'pure-button pure-button-primary sign')
-else
  =link_to('Log out' , logout_path, method:"delete" , :class => 'pure-button pure-button-primary sign')

app/views/bios/index.html.slim
=render 'header'
.banner
  .banner-transparent
    h1.banner-head
      | BioのBio-Zによる
      br/
      | BioのためのWebアプリ
.l-content
  .information.pure-g
    .pure-u-1
      .l-box
        h3.information-head News & Topics
        p
          | 12月25日　南立くんが無事出産しました。（test）
        p
          | 1月5日　　南立くんが東京刑務所へ連行されました。　(test)
        p
          | 1月26日　 南立くんが脱獄しました。(test)
    .pure-u-1
      .l-box
        h3.information-head あなたへのお知らせ
        p
          | 3月14日までに奨学金の書類を提出してください。
    .pure-u-1
      .l-box
        h3.information-head メモ
        ul#ideaList
        textarea#idea cols="100" rows="8" style="width:600px;height:150px;" 
        p
          input#submit.pure-button type="button" value="投稿" /
          input#delete.pure-button type="button" value="削除" /

=render 'footer'

app/views/kakomons/index.html.slim
#layout.content.pure-g
  #nav.pure-u
    a.nav-menu-button href="#"  Menu
    .nav-inner
      button.primary-button.pure-button Compose
      .pure-menu
        ul.pure-menu-list
          li.pure-menu-item
            a.pure-menu-link href="#" 
              | Inbox
              span.email-count (2)
          li.pure-menu-item
            a.pure-menu-link href="#"  Important
          li.pure-menu-item
            a.pure-menu-link href="#"  Sent
          li.pure-menu-item
            a.pure-menu-link href="#"  Drafts
          li.pure-menu-item
            a.pure-menu-link href="#"  Trash
          li.pure-menu-heading Labels
          li.pure-menu-item
            a.pure-menu-link href="#" 
              span.email-label-personal
              | Personal
          li.pure-menu-item
            a.pure-menu-link href="#" 
              span.email-label-work
              | Work
          li.pure-menu-item
            a.pure-menu-link href="#" 
              span.email-label-travel
              | Travel
  #list.pure-u-1
    .email-item.email-item-selected.pure-g
      .pure-u
        img.email-avatar alt=("Tilo Mitra's avatar") height="64" src="img/common/tilo-avatar.png" width="64" /
      .pure-u-3-4
        h5.email-name Tilo Mitra
        h4.email-subject Hello from Toronto
        p.email-desc
          | Hey, I just wanted to check in with you from Toronto. I got here earlier today.
    .email-item.email-item-unread.pure-g
      .pure-u
        img.email-avatar alt=("Eric Ferraiuolo's avatar") height="64" src="img/common/ericf-avatar.png" width="64" /
      .pure-u-3-4
        h5.email-name Eric Ferraiuolo
        h4.email-subject Re: Pull Requests
        p.email-desc
          | Hey, I had some feedback for pull request #51. We should center the menu so it looks better on mobile.
    .email-item.email-item-unread.pure-g
      .pure-u
        img.email-avatar alt=("YUI's avatar") height="64" src="img/common/yui-avatar.png" width="64" /
      .pure-u-3-4
        h5.email-name YUI Library
        h4.email-subject You have 5 bugs assigned to you
        p.email-desc
          | Duis aute irure dolor in reprehenderit in voluptate velit essecillum dolore eu fugiat nulla.
    .email-item.pure-g
      .pure-u
        img.email-avatar alt=("Reid Burke's avatar") height="64" src="img/common/reid-avatar.png" width="64" /
      .pure-u-3-4
        h5.email-name Reid Burke
        h4.email-subject Re: Design Language
        p.email-desc
          | Excepteur sint occaecat cupidatat non proident, sunt in culpa.
    .email-item.pure-g
      .pure-u
        img.email-avatar alt=("Andrew Wooldridge's avatar") height="64" src="img/common/andrew-avatar.png" width="64" /
      .pure-u-3-4
        h5.email-name Andrew Wooldridge
        h4.email-subject YUI Blog Updates?
        p.email-desc
          | Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.
    .email-item.pure-g
      .pure-u
        img.email-avatar alt=("Yahoo! Finance's Avatar") height="64" src="img/common/yfinance-avatar.png" width="64" /
      .pure-u-3-4
        h5.email-name Yahoo! Finance
        h4.email-subject How to protect your finances from winter storms
        p.email-desc
          | Mauris tempor mi vitae sem aliquet pharetra. Fusce in dui purus, nec malesuada mauris.
    .email-item.pure-g
      .pure-u
        img.email-avatar alt=("Yahoo! News' avatar") height="64" src="img/common/ynews-avatar.png" width="64" /
      .pure-u-3-4
        h5.email-name Yahoo! News
        h4.email-subject Summary for April 3rd, 2012
        p.email-desc
          | We found 10 news articles that you may like.
  #main.pure-u-1
    .email-content
      .email-content-header.pure-g
        .pure-u-1-2
          h1.email-content-title Hello from Toronto
          p.email-content-subtitle
            | From
            a Tilo Mitra
            | at
            span 3:56pm, April 3, 2012
        .email-content-controls.pure-u-1-2
          button.secondary-button.pure-button Reply
          button.secondary-button.pure-button Forward
          button.secondary-button.pure-button Move to
      .email-content-body
        p
          | Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
        p
          | Duis aute irure dolor in reprehenderit in voluptate velit essecillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        p
          | Aliquam ac feugiat dolor. Proin mattis massa sit amet enim iaculis tincidunt. Mauris tempor mi vitae sem aliquet pharetra. Fusce in dui purus, nec malesuada mauris. Curabitur ornare arcu quis mi blandit laoreet. Vivamus imperdiet fermentum mauris, ac posuere urna tempor at. Duis pellentesque justo ac sapien aliquet egestas. Morbi enim mi, porta eget ullamcorper at, pharetra id lorem.
        p
          | Donec sagittis dolor ut quam pharetra pretium varius in nibh. Suspendisse potenti. Donec imperdiet, velit vel adipiscing bibendum, leo eros tristique augue, eu rutrum lacus sapien vel quam. Nam orci arcu, luctus quis vestibulum ut, ullamcorper ut enim. Morbi semper erat quis orci aliquet condimentum. Nam interdum mauris sed massa dignissim rhoncus.
        p
          | Regards,
          br/
          | Tilo
script src="http://yui.yahooapis.com/3.17.2/build/yui/yui-min.js" 
/ javascript:
/   | YUI().use('node-base', 'node-event-delegate', function (Y) {
/ 
/       | var menuButton = Y.one('.nav-menu-button'),
/           | nav        = Y.one('#nav');
/ 
/       /!/ Setting the active class name expands the menu vertically on small screens.
/       | menuButton.on('click', function (e) {
/           | nav.toggleClass('active');
/       | });
/ 
/       /!/ Your application code goes here...
/ 
/   | });

app/views/laboratories/index.html.slim
#layout
  /! Menu toggle
  a#menuLink.menu-link href="#menu" 
    /! Hamburger icon
    span
  #menu
    .pure-menu
      li.pure-menu-heading 研究室紹介
      ul.pure-menu-list
        li.pure-menu-item.drop-menu
          p 教授
          ul.child.pure-menu-list
            - @professors.each do |professor|
              - if professor.category == 1
                li.pure-menu-item
                =link_to("#{professor.name}研究室" , laboratory_path(professor.id), :class => 'pure-menu-link')
        li.pure-menu-item.drop-menu
          p 准教授
          ul.child.pure-menu-list
            - @professors.each do |professor|
              - if professor.category ==2
                li.pure-menu-item
                =link_to("#{professor.name}研究室" , laboratory_path(professor.id), :class => 'pure-menu-link')

        li.pure-menu-item.drop-menu
          p 助教授
          ul.child.pure-menu-list
            - @professors.each do |professor|
              - if professor.category ==3
                li.pure-menu-item
                =link_to("#{professor.name}研究室" , laboratory_path(professor.id), :class => 'pure-menu-link')
  #main
    #top.header
      h1 研究室の紹介ページ
      h2 これは研究室の紹介ページです。
    .content
      h2#profile.content-subhead プロフィール
      ul
        li 名前
        p 島井　尚輝
        li 出身
        p 福岡県　糟屋郡　宇美町
        li 大学
        p 九州工業大学　情報工学部　生命情報工学科　3年　矢田研究室
        li 研究
        p ゲノム情報を可視化してブラウザ上に表示させるWebアプリケーション開発
        li 趣味
        p 音楽　卓球　バドミントン　ビリヤード　プログラミング
        li 得意な技術
        p Webのフロントエンド(HTML , CSS , JavaScript)
        li 興味のある技術
        p Rails , Redis , AWS , CoffeeScript , Compass , React.js , AnglarJS , Sass , Underscore.js , Backbone.js , gulp , chef , grunt , PhotoShop , Illustrator , Node.js
        li 好きな言葉
        p 出過ぎた杭は打たれない。武器は走りながら拾え。
      h2#Bio-Z.content-subhead Bio-Z
      p
        | Bio-Zとは当学科内でプログラミング、アプリ開発を行っている団体です。僕が2016年の代表をしていて、現時点の活動としてはWeb制作の基礎知識をつけてもらうために当学科の学部1年から3年を対象にしてWeb開発講習会を行っています。Bio-Zの活動は生命の学科内のプログラミングスキルの向上が目的で、現メンバーが活躍して少しでも多くの人に知ってもらってこれから先Bio-Zに加入する人が増えていけばいいなと思っています。
      br/
      .pure-g
        .pure-u-1-2
          =image_tag("Bio-Z/f.jpg" , :class => 'pure-img-responsive')
        .pure-u-1-2
          =image_tag("Bio-Z/e.jpg" , :class => 'pure-img-responsive')
        .pure-u-1-2
          =image_tag("Bio-Z/b.jpg" , :class => 'pure-img-responsive')
        .pure-u-1-2
          =image_tag("Bio-Z/h.jpg" , :class => 'pure-img-responsive')
      h2#Yada_lab.content-subhead 矢田研究室
      p
        | 矢田研究室では主にバイオインフォマティクスの研究を行っています。
      p
        | 僕の研究テーマは「
        strong ゲノム情報を可視化してブラウザ上に表示させるWebアプリケーション開発
        | 」です。
      p
        strong キーワード
        p ゲノム ゲノム生物学 アノテーション 遺伝子 プロモーター 遺伝子発見 配列解析 機械学習 発現制御 合成生物学 アルゴリズム ヒト アラインメント 転写制御
      .pure-g
        .pure-u-1-2
          =image_tag("Yada_lab/o.jpg" , :class => 'pure-img-responsive')
        .pure-u-1-2
          =image_tag("Yada_lab/m.jpg" , :class => 'pure-img-responsive')
          =image_tag("Yada_lab/n.jpg" , :class => 'pure-img-responsive')

app/views/laboratories/show.html.slim
#main
  #top.header
    h1 #{@professor.name}研究室

app/views/users/_footer.html.slim
.footer.l-box
  address
    | &copy 2016 created by Bio-Z We部　

app/views/users/_header.html.slim
.pure-menu.pure-menu-horizontal
  a.pure-menu-heading href="./"
    =image_tag("icons3/Primary.png")
  ul.pure-menu-list
    li.pure-menu-item
      =link_to('研究室' , laboratories_path , :class => 'pure-menu-link')
    li.pure-menu-item
      =link_to('過去問道場' , kakomons_path , :class => 'pure-menu-link')
    li.pure-menu-item
      =link_to('就職' , jobs_path , :class => 'pure-menu-link')
    li.pure-menu-item.pure-menu-has-children.pure-menu-allow-hover
      p.pure-menu-link
       | コンテンツ
      ul.pure-menu-children
        li.pure-menu-item
          =link_to('温度、湿度測定', {} , :class => 'pure-menu-link')
        li.pure-menu-item
          =link_to('脈拍の測定', {} ,:class => 'pure-menu-link')
        li.pure-menu-item.pure-menu-disabled
          =link_to('coming soon..', {}, :class => 'pure-menu-link')
    li.pure-menu-item.pure-menu-has-children.pure-menu-allow-hover
      p.pure-menu-link
        | リンク
      ul.pure-menu-children
        li.pure-menu-item
          =link_to('moodle', 'http://mi.el.kyutech.ac.jp/course/index.php?categoryid=8' , :class => 'pure-menu-link')
        li.pure-menu-item
          =link_to('livecampus', 'https://virginia.jimu.kyutech.ac.jp/portal/init.do?userDivision=2&locale=ja' ,:class => 'pure-menu-link')
        li.pure-menu-item
          =link_to('オンラインガイド', 'https://onlineguide.isc.kyutech.ac.jp/guide2015/', :class => 'pure-menu-link')
-if !logged_in?
  =link_to('Log in' , login_path, :class => 'pure-button pure-button-primary sign')
-else
  =link_to('Log out' , logout_path, method:"delete"  , :class => 'pure-button pure-button-primary sign')

app/views/users/new.html.slim
=render 'header'
.pure-form.pure-form-aligned
  =form_for(@user) do |f|
    fieldset
      .pure-control-group
        =f.label :name 
        =f.text_field :name , :placeholder => 'Username'
      .pure-control-group
        =f.label :email
        =f.text_field :email , :placeholder => 'Email Address'
      .pure-control-group
        =f.label :password
        =f.password_field :password , :placeholder => 'password'
      .pure-control-group
        =f.label :password_confirmation,"Confirmation"
        =f.password_field :password_confirmation , :placeholder => 'Please type one more'
      .pure-controls
        =f.submit("Sign up",:class => "pure-button pure-button-primary")

app/views/users/show.html.slim
- provide(:title, @user.name)

/ h1 ようこそ#{@user.name}さん^ ^

/ .center
/   = link_to "Go to BioWeb!!", { :controller => "bios", :action => "index" }, { :class => "pure-button pure-button-primary size" } 

=render 'header'
.banner
  .banner-transparent
    h1.banner-head
      | ようこそ#{@user.name}さん^ ^
.l-content
  .information.pure-g
    .pure-u-1
      .l-box
        h3.information-head News & Topics
        p
          | 12月25日　南立くんが無事出産しました。（test）
        p
          | 1月5日　　南立くんが東京刑務所へ連行されました。　(test)
        p
          | 1月26日　 南立くんが脱獄しました。(test)
    .pure-u-1
      .l-box
        h3.information-head あなたへのお知らせ
        p
          | 3月14日までに奨学金の書類を提出してください。
    .pure-u-1
      .l-box
        h3.information-head メモ
        ul#ideaList
        textarea#idea cols="100" rows="8" style="width:600px;height:150px;" 
        p
          input#submit.pure-button type="button" value="投稿" /
          input#delete.pure-button type="button" value="削除" /

=render 'footer'